version: "3"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    env_file:
      - .flaskenv
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - minio

  db:
    image: mysql:8.0
    # restart: always
    # user: "${UID}:${GID}"
    env_file: .flaskenv

    # command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/app
      - mysql-data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8000:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .flaskenv
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file: .flaskenv
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  create_minio_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY})
      do echo '...waiting...' && sleep 2;
      done;
      /usr/bin/mc mb --ignore-existing local/emoji;
      "

volumes:
  mysql-data:
  rabbitmq-data:
  minio-data:
